model_list:  
  - model_name: gpt-5-mini
    litellm_params:  
      model: bedrock/global.anthropic.claude-sonnet-4-5-20250929-v1:0
  - model_name: embedding-model
    litellm_params:
      model: openai/text-embedding-3-large

vector_store_registry:
  - vector_store_name: "vertex-ai-litellm-website-knowledgebase"
    litellm_params:
      vector_store_id: "litellm-docs_1761094140318"
      custom_llm_provider: "vertex_ai/search_api"
      vertex_project: "test-vector-store-db"
      vertex_location: "global"